//! Output transform and file encoding.

use std::path::Path;

use latent_image::ImageBuf;
use latent_image::color::{self, Mat3};

/// sRGB OETF: encode a linear-light value into gamma-encoded sRGB.
///
/// A near-2.2 power curve with a small linear segment near black. Applied last,
/// on the way out, to turn linear-light pixels into display/file values.
///
/// Transfer function defined by the sRGB standard, IEC 61966-2-1.
pub fn srgb_encode(c: f32) -> f32 {
    if c <= 0.0031308 {
        12.92 * c
    } else {
        1.055 * c.powf(1.0 / 2.4) - 0.055
    }
}

/// Inverse sRGB OETF: decode a gamma-encoded sRGB value back to linear light.
pub fn srgb_decode(c: f32) -> f32 {
    if c <= 0.04045 {
        c / 12.92
    } else {
        ((c + 0.055) / 1.055).powf(2.4)
    }
}

/// Highlight rolloff, **anchored at white**: values up to the knee (just below
/// 1.0) pass through unchanged, and everything from there up — including headroom
/// above 1.0 — is compressed smoothly toward, but never reaching, 1.0.
///
/// The knee sits at 0.98 so display `[0, 1]` stays faithful to within ~1 code
/// (white maps to 254, not 255), while highlights above 1.0 keep a gradient
/// instead of clamping flat. That gradient is necessarily tiny at 8 bits — it
/// lives in the top code or two — but is real at 16 bits ([`save_16`]), which is
/// what it exists for. (You cannot keep white at *exactly* 255 and also show a
/// headroom gradient in a fixed-range output; 0.98 is the
/// faithful-within-tolerance compromise.)
pub fn highlight_rolloff(x: f32) -> f32 {
    const KNEE: f32 = 0.98;
    if x <= KNEE {
        x
    } else {
        let span = 1.0 - KNEE;
        let excess = x - KNEE;
        KNEE + span * (excess / (excess + span))
    }
}

/// The full output transform for one working-space pixel: working → linear sRGB,
/// highlight rolloff, sRGB OETF, clamped to display `[0, 1]`. Shared by the 8-bit
/// and 16-bit encoders so they agree exactly bar quantization.
fn to_display(working: [f32; 3], to_srgb: &Mat3) -> [f32; 3] {
    let lin = to_srgb.mul_vec(working);
    std::array::from_fn(|c| srgb_encode(highlight_rolloff(lin[c])).clamp(0.0, 1.0))
}

/// Apply the output transform to a whole working-space image and return row-major
/// 8-bit sRGB bytes (`RGBRGB…`).
///
/// This is *the* output path — both the saved 8-bit file ([`save`]) and the live
/// editor preview go through it, so the preview matches the file by construction.
pub fn to_srgb8(img: &ImageBuf) -> Vec<u8> {
    let to_srgb = color::linear_working_to_linear_srgb();
    let mut bytes = Vec::with_capacity(img.len() * 3);
    for y in 0..img.height() {
        for x in 0..img.width() {
            for v in to_display(img.get(x, y), &to_srgb) {
                bytes.push((v * 255.0 + 0.5) as u8);
            }
        }
    }
    bytes
}

/// Encode a linear-light **working-space** image to 8-bit sRGB and write it to
/// `path`.
///
/// Converts the working space (wide-gamut linear) to linear sRGB, rolls off
/// highlights into display range, gamma-encodes (sRGB OETF), and quantizes to
/// 8 bits via [`to_srgb8`]. The format is chosen from the path's extension
/// (e.g. `.jpg`, `.png`, `.tiff`); an sRGB ICC profile is embedded.
pub fn save(img: &ImageBuf, path: &Path) -> image::ImageResult<()> {
    let out = image::RgbImage::from_raw(img.width(), img.height(), to_srgb8(img))
        .expect("buffer length matches the image dimensions");
    save_buffer_with_icc(&out, path)
}

/// Encode the image to **16-bit** sRGB (same output transform as [`save`]) and
/// write it to `path`. The extra depth preserves the gradients a wide-gamut,
/// highlight-rolled working pipeline produces, which 8 bits would band.
pub fn save_16(img: &ImageBuf, path: &Path) -> image::ImageResult<()> {
    let to_srgb = color::linear_working_to_linear_srgb();
    let mut out = image::ImageBuffer::<image::Rgb<u16>, Vec<u16>>::new(img.width(), img.height());
    for y in 0..img.height() {
        for x in 0..img.width() {
            let d = to_display(img.get(x, y), &to_srgb);
            let rgb = std::array::from_fn(|c| (d[c] * 65535.0 + 0.5) as u16);
            out.put_pixel(x, y, image::Rgb(rgb));
        }
    }
    save_buffer_with_icc(&out, path)
}

/// The sRGB ICC profile bytes for tagging output — our output transform produces
/// sRGB, so this matches the data. Generated by `moxcms` (a real, validated
/// profile, not hand-rolled).
fn srgb_icc() -> Vec<u8> {
    moxcms::ColorProfile::new_srgb()
        .encode()
        .expect("encode sRGB ICC profile")
}

/// Write an 8- or 16-bit RGB buffer to `path` with the sRGB ICC profile embedded
/// via the per-format encoder (the high-level `save` can't carry ICC). Format is
/// chosen by extension; an unknown extension falls back to an untagged save.
fn save_buffer_with_icc<P>(
    buf: &image::ImageBuffer<P, Vec<P::Subpixel>>,
    path: &Path,
) -> image::ImageResult<()>
where
    P: image::PixelWithColorType,
    [P::Subpixel]: image::EncodableLayout,
{
    use image::ImageEncoder;
    let icc = srgb_icc();
    let ext = path
        .extension()
        .and_then(|e| e.to_str())
        .unwrap_or_default()
        .to_ascii_lowercase();
    match ext.as_str() {
        "png" => {
            let mut enc = image::codecs::png::PngEncoder::new(std::fs::File::create(path)?);
            enc.set_icc_profile(icc)
                .map_err(image::ImageError::Unsupported)?;
            buf.write_with_encoder(enc)
        }
        "tif" | "tiff" => {
            let mut enc = image::codecs::tiff::TiffEncoder::new(std::fs::File::create(path)?);
            enc.set_icc_profile(icc)
                .map_err(image::ImageError::Unsupported)?;
            buf.write_with_encoder(enc)
        }
        "jpg" | "jpeg" => {
            let mut enc = image::codecs::jpeg::JpegEncoder::new(std::fs::File::create(path)?);
            enc.set_icc_profile(icc)
                .map_err(image::ImageError::Unsupported)?;
            buf.write_with_encoder(enc)
        }
        _ => buf.save(path),
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn endpoints_are_fixed() {
        assert_eq!(srgb_encode(0.0), 0.0);
        assert!((srgb_encode(1.0) - 1.0).abs() < 1e-6);
    }

    #[test]
    fn encode_then_decode_round_trips() {
        for &v in &[0.0, 0.001, 0.0031308, 0.05, 0.18, 0.5, 0.9, 1.0] {
            let back = srgb_decode(srgb_encode(v));
            assert!((back - v).abs() < 1e-5, "round-trip drift at {v}: {back}");
        }
    }

    #[test]
    fn encoding_brightens_midtones() {
        // Gamma encoding lifts mid-gray well above its linear value.
        assert!(srgb_encode(0.18) > 0.4);
    }

    #[test]
    fn highlight_rolloff_is_identity_below_knee_and_monotone_above() {
        assert_eq!(highlight_rolloff(0.0), 0.0);
        assert_eq!(highlight_rolloff(0.9), 0.9); // below the 0.98 knee: unchanged
        // From the knee up: strictly increasing, always < 1.0 (room kept for more),
        // and white (1.0) barely moves so display stays faithful.
        let (a, b, c) = (
            highlight_rolloff(1.0),
            highlight_rolloff(2.0),
            highlight_rolloff(8.0),
        );
        assert!(0.98 < a && a < b && b < c && c < 1.0, "{a} {b} {c}");
    }

    #[test]
    fn save_writes_a_readable_image() {
        // Neutrals are invariant under the working→sRGB transform, so they
        // exercise the encode + rolloff + file round-trip without depending on the
        // working space's primaries.
        let mut img = ImageBuf::new(2, 2);
        img.set(0, 0, [0.0, 0.0, 0.0]); // black
        img.set(1, 0, [1.0, 1.0, 1.0]); // sensor white (rolled off)
        img.set(0, 1, [0.5, 0.5, 0.5]); // mid-gray (below the knee)
        img.set(1, 1, [2.0, 2.0, 2.0]); // highlight headroom

        let path = std::env::temp_dir().join("latent_export_save_test.png");
        save(&img, &path).expect("save should succeed");

        let loaded = image::open(&path)
            .expect("written file should open")
            .to_rgb8();
        assert_eq!(loaded.dimensions(), (2, 2));
        assert_eq!(loaded.get_pixel(0, 0), &image::Rgb([0, 0, 0])); // black
        // Mid-gray (below the knee): faithful, 0.5 linear → sRGB OETF = 188.
        assert_eq!(loaded.get_pixel(0, 1).0, [188, 188, 188]);
        // Display white (1.0) is faithful to within one code (254, not 255) — the
        // rolloff barely moves it — and the >1.0 headroom maps strictly brighter,
        // to 255. Pinned exactly so a future rolloff change can't silently drift.
        assert_eq!(loaded.get_pixel(1, 0).0[0], 254, "white"); // working 1.0
        assert_eq!(loaded.get_pixel(1, 1).0[0], 255, "headroom"); // working 2.0

        std::fs::remove_file(&path).ok();
    }

    #[test]
    fn save_16_writes_a_true_16bit_file() {
        let mut img = ImageBuf::new(2, 1);
        img.set(0, 0, [0.0, 0.0, 0.0]);
        img.set(1, 0, [0.5, 0.5, 0.5]);
        let path = std::env::temp_dir().join("latent_export_save16_test.tiff");
        save_16(&img, &path).expect("save_16 should succeed");

        let loaded = image::open(&path).expect("written file should open");
        assert!(
            matches!(loaded.color(), image::ColorType::Rgb16),
            "expected 16-bit, got {:?}",
            loaded.color()
        );
        let px = loaded.to_rgb16();
        assert_eq!(px.get_pixel(0, 0).0, [0, 0, 0]);
        // 0.5 linear → sRGB OETF ≈ 0.7354 → ~48196 at 16 bits — and not the 8-bit
        // value scaled up (188·257), proving real 16-bit precision.
        let gray = px.get_pixel(1, 0).0[0];
        assert!((gray as i32 - 48196).abs() < 200, "gray16: {gray}");
        assert_ne!(gray, 188 * 257, "carries 16-bit precision, not 8-bit");

        std::fs::remove_file(&path).ok();
    }

    #[test]
    fn save_embeds_a_readable_icc_profile() {
        use image::ImageDecoder;
        let mut img = ImageBuf::new(1, 1);
        img.set(0, 0, [0.5, 0.5, 0.5]);
        let path = std::env::temp_dir().join("latent_export_icc_test.png");
        save(&img, &path).expect("save should succeed");

        let mut decoder = image::codecs::png::PngDecoder::new(std::io::BufReader::new(
            std::fs::File::open(&path).unwrap(),
        ))
        .expect("decode png");
        let embedded = decoder.icc_profile().expect("icc read ok");
        assert!(
            embedded.is_some_and(|p| !p.is_empty()),
            "output should carry an embedded ICC profile"
        );
        std::fs::remove_file(&path).ok();
    }

    #[test]
    fn save_16_embeds_a_readable_icc_profile() {
        // The 16-bit TIFF path must also carry the profile (a different encoder
        // than PNG), so the tag isn't silently dropped for the high-bit export.
        use image::ImageDecoder;
        let mut img = ImageBuf::new(1, 1);
        img.set(0, 0, [0.5, 0.5, 0.5]);
        let path = std::env::temp_dir().join("latent_export_icc16_test.tiff");
        save_16(&img, &path).expect("save_16 should succeed");

        let mut decoder = image::codecs::tiff::TiffDecoder::new(std::io::BufReader::new(
            std::fs::File::open(&path).unwrap(),
        ))
        .expect("decode tiff");
        let embedded = decoder.icc_profile().expect("icc read ok");
        assert!(
            embedded.is_some_and(|p| !p.is_empty()),
            "16-bit TIFF output should carry an embedded ICC profile"
        );
        std::fs::remove_file(&path).ok();
    }
}
